### ISSUE TITLE
ufs-bundle broken after switching to fms/2023.04 in fv3-jedi

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA/ufs-bundle#69]
After https://github.com/orgs/JCSDA-internal/discussions/139, ufs-bundle no longer builds: https://github.com/JCSDA/ufs-bundle/actions/runs/9754804727.
Build fails with:
```
ld: ld: ../../../Depends/lib/libfv3atm.a(module_fcst_grid_comp.F90.o): in function `module_fcst_grid_comp_mp_fcst_initialize_':
/mnt/addon/jedi-run/ufs-bundle/ufs-bundle/ufs-weather-model/FV3/module_fcst_grid_comp.F90:647: undefined reference to `fmsconstants_mp_fmsconstants_init_'
ld: /mnt/addon/jedi-run/ufs-bundle/ufs-bundle/ufs-weather-model/FV3/module_fcst_grid_comp.F90:815: undefined reference to `data_override_mod_mp_data_override_init_'
ld: ../../../Depends/lib/libfv3atm.a(module_fcst_grid_comp.F90.o): in function `module_fcst_grid_comp_mp_fcst_initialize_':
/mnt/addon/jedi-run/ufs-bundle/ufs-bundle/ufs-weather-model/FV3/module_fcst_grid_comp.F90:647: undefined reference to `fmsconstants_mp_fmsconstants_init_'
ld: /mnt/addon/jedi-run/ufs-bundle/ufs-bundle/ufs-weather-model/FV3/module_fcst_grid_comp.F90:815: undefined reference to `data_override_mod_mp_data_override_init_'
ld: ../../../Depends/lib/libfv3atm.a(atmos_model.F90.o): in function `atmos_model_mod_mp_atmos_model_init_':
/mnt/addon/jedi-run/ufs-bundle/ufs-bundle/ufs-weather-model/FV3/atmos_model.F90:626: undefined reference to `block_control_mod_mp_define_blocks_packed_'
../../../Depends/lib/libfv3atm.a(atmos_model.F90.o): in function `atmos_model_mod_mp_atmos_model_init_':
/mnt/addon/jedi-run/ufs-bundle/ufs-bundle/ufs-weather-model/FV3/atmos_model.F90:626: undefined reference to `block_control_mod_mp_define_blocks_packed_'
ld: ../../../Depends/lib/libstochastic_physics.a(cellular_automata_global.F90.o): in function `cellular_automata_global_mod_mp_cellular_automata_global_':
/mnt/addon/jedi-run/ufs-bundle/ufs-bundle/ufs-weather-model/stochastic_physics/cellular_automata_global.F90:153: undefined reference to `block_control_mod_mp_define_blocks_packed_'
```
I am guessing there's something interesting happening because of differing fv3 versions between jedi-bundle and ufs-bundle and changes in https://github.com/JCSDA-internal/fv3-jedi/pull/812, but I don't know enough to diagnose this.
@mark-a-potts, @CoryMartin-NOAA, @aerorahul: do you have an idea what could be wrong and how to fix this?

**Comment by climbfuji** [comment]
We should note that until yesterday, the ufs-bundle code using the same fv3 dycore code as it is using today (? correct ?) with the same version of FMS it is using today (`fms@2023.04`) worked fine.

???

**Comment by mark-a-potts** [comment]
I am not sure if the ufs-weather-model has been updated to work with fms/2023.04 yet. If it has not, then that would be the reason for the error.

**Comment by mark-a-potts** [comment]
Well, I just looked and the wm has been upgraded to 2023.04. I'll look further into the artifacts.
